<?php

return [
    'title' => 'Produtores',
    'ngongo' => 'A NGONGO Filmes foi criada por Mariana Luiza, com o objetivo de realizar projetos literários e audiovisuais relacionados a questões étnicas, sociais e de gênero. Ao longo dos anos, a produtora prestou serviços para Bananeira Filmes, Preta Portê Filmes, Conspiração Filmes e Coqueirão Pictures. Em 2017, produziu  o curta-metragem de ficção "Casca de Baobá" (12 min). O projeto foi contemplado no Edital do SAv/Minc - Curta Afirmativo (2014). Casca de Baobá foi exibido em diversos festivais no Brasil e no mundo, recebendo 6 prêmios. Em 2010, a produtora produziu o média-metragem A B Ser (52 min). O projeto foi contemplado no edital Filma Brasil (Lei Rouanet). O filme foi licenciado para o canal Futura.',
    'carapia' => 'A Carapiá Filmes nasceu do desejo de fazer cinema de forma colaborativa e humana. Buscamos nas nossas produções impulsionar diretores emergentes latino-americanos com o intuito de produzir filmes a partir de novas ideias e olhares. Temos interesses em projetos encabeçados por pessoas historicamente invisibilizadas e com temáticas de forte apelo artístico, político e social. Para contribuir para uma nova forma de pensar e transformar a nossa realidade a partir do cinema, criamos o nosso núcleo germinAÇÃO, espaço para a formação e o desenvolvimento de pessoas no âmbito do audiovisual e do cinema. Atualmente desenvolvemos e produzimos os projetos: O segredo de Sikán com Everlane Moraes (Brlab, TorinoFilmLab, Brasil CineMundi, entre outros), Maestra com Bruna Piantino (contemplado na Lei Municipal de Incentivo à Cultura de Belo Horizonte) e A Cor da Margem (BioBioLab, Brasil CineMundi, Miradas Doc, entre outros) com Mariana Luiza, uma coprodução entre Brasil-França.',
    'vidigal' => 'Fernanda é especializada em produção cinematográfica na EICTV/Cuba e graduada em Cinema e Audiovisual no Centro Universitário UNA/Brasil. Desde 2013 trabalha na produção cinematográfica, onde já trabalhou em dez longas-metragens. Fernanda faz parte da rede Berlinale Talents Guadalajara (México) e Talents Paradiso (Brasil). Em 2020 ela criou sua produtora Carapiá Filmes, em Belo Horizonte. Em 2021 foi convidada pelo Projeto Paradiso para participar do Visitors Programme do Mercado de Co-Produção da Berlinale (Alemanha) e fez parte do Comitê de Seleção de Projetos Estrangeiros do BrLab Features (Brasil). Atualmente, Fernanda está desenvolvendo três projetos com três diretoras brasileiras, tendo uma coprodução com a França, e ganhando fundos como Hubert Bals Fund, BH nas Telas e outros.
Site: http://fernandavidigal.com.br/
IMDb: https://www.imdb.com/name/nm11710290/?ref_=nv_sr_srsg_0
Linkedin: https://www.linkedin.com/in/fernanda-vidigal/',
    'parati' => 'Parati Films, produtora francesa sediada na região Les Pays de la Loire na França, trabalha no mercado audiovisual desde 2006. Recentemente, abriu uma filial no Rio de Janeiro, Brasil. Em sua missão de valorizar o cinema autoral e as obras independentes na América Latina, com o apoio de seus outros departamentos, seu trabalho se concentra principalmente na co-produção de obras entre a América Latina e a Europa. Durante muitos anos, a produtora optou por se ausentar da produção direta de filmes, a fim de se concentrar especialmente no Brasil CineMundi e La Fabrique des cinemas du Monde. Em 2022, a empresa volta ao mercado com toda sua energia e experiência para a produção e co-produção. ',
    'roinssart' => 'Séverine iniciou a Parati Films em 2006, com o objetivo de criar um programa de intercâmbio cinematográfico, sobretudo entre a França, a Europa e os países da América Latina. O dinamismo das 4 áreas da Parati Films: - organização de eventos e prestação de serviços, legendagem & tradução, produção e gestão de produção pedagógica, tem resultado em colaborações com inúmeros profissionais do mundo do cinema e de festivais internacionais. Um desses exemplos é o Festival de Cinema de Cannes, onde desde 2011 Parati tem sido o parceiro oficial do Institut Francais na seleção de projetos e na coordenação do programa La Fabrique des Cinémas du Monde - e também permitiu a participação em projetos de co-produção. Parati está atualmente a co-produzir o projeto de documentário brasileiro “A Cor da Margem” e um projeto de ficção do Paraguai. Finalmente, Séverine acaba de criar o Crok Cine, programa para a educação - através de imagens, na França e internacionalmente, baseado na mistura social.'
    ];


