<?php

return [
    'title' => 'Pesquisadores',
    'Thula' => 'Professora-adjunta de Direito Constitucional (PUC-Rio). Coordenadora do Programa de Pós-Graduação em Direito e Coordenadora Geral do NIREMA (Núcleo Interdisciplinar de Reflexão e Memória Afrodescendente). Coordenadora do Direito em Pretuguês: Grupo de Pesquisa em estudos Ladino-Amefricanos e Afrodiaspóricos. Professora Visitante Jr. no African Gender Institute, University of Cape Town (CAPES/Print/2020). Jovem Cientista do Nosso Estado (FAPERJ- 2022/2025). Integrante do Conselho do Instituto Clima e Sociedade (ICS), da Assembleia Geral da Anistia Internacional no Brasil e associada de CRIOLA. Mãe da Dandara e bailarina. ',
    'Stephanie' => 'Stephane Ramos é Graduada e Mestra em História pela Universidade Federal do Rio de Janeiro e Doutoranda em História pela Universidade de Brasília. É professora e pesquisadora, com enfoque em história da educação no Brasil e experiências de liberdade entre os séculos XIX e XX.',
    'Mateus' => 'Mateus Alisson é graduando em Licenciatura e Bacharelado em História pela Universidade Federal da Bahia. Passou pelo Instituto Federal da Bahia (Simões Filho), onde aprendeu sobre os limites e potencialidades da história, cultura e produção de conhecimento. Atualmente, trabalha na área de Enviroment, Social and Governance do Nubank.',
    'Itan' => 'Doutorando em História Social pela Universidade Federal da Bahia (UFBA), mestre em História Social pela Universidade Federal Fluminense (UFF), e membro do Laboratório de História Oral e Imagem (LABHOI/UFF). Integrou também, entre 2016 e 2020, o grupo de pesquisa em Botânica Aplicada, Avaliação Antropológica, Socioambiental e Educacional do Instituto de Pesquisa Jardim Botânico do Rio de Janeiro. Graduado pelo curso de História (bacharelado e licenciatura), UFBA. Graduado pelo Bacharelado Interdisciplinar (B.I.) em Humanidades, pelo Instituto de Humanidades, Artes e Ciências professor Milton Santos - UFBA. ',
    'Fernanda' => 'Doutoranda e mestra em Direito, Estado e Constituição pela Universidade de Brasília (UnB). Professora da EDAP/IDP. Pesquisadora vinculada aos grupos Asa Branca de Criminologia (UNICAP/UFPE), Maré - Núcleo de Estudos e Pesquisa em Cultura Jurídica e Atlântico Negro (UnB) e Centro de Estudos em Desigualdade e Discriminação - CEDD (UnB). Foi consultora, junto ao CNJ e ao PNUD, no programa Justiça Presente. Possui experiência nas seguintes temáticas: criminologia; direito e relações raciais; história do direito; direitos humanos.',
    'Bruna' => 'Professora do Departamento de Direito da PUC Rio, doutoranda em Direito na mesma instituição, mestra em Direito pela UnB. Foi coordenadora da área de Direitos do Instituto de Estudos da Religião (ISER) e professora substituta na Universidade Federal da Bahia (UFBA). Atualmente compõe o Grupo Clandestino de Estudos em Controle, Cidade e Prisões e o LabCap - Laboratório de Críticas e Alternativas à Prisão. Na universidade e no terceiro setor, atuou em assessoria popular e produção de conhecimento. Tem especial interesse nos cruzamentos entre direito e relações raciais, história social do direito e da justiça, criminologia e direito penal.',
    'Ana' => 'Ana Flávia Magalhães Pinto é historiadora, com formação interdisciplinar em Comunicação e Literatura. Desde 2018, atua como professora do Departamento de História da Universidade de Brasília (UnB). É autora de “Escritos de Liberdade: literatos negros, racismo e cidadania no Brasil oitocentista” (Ed. Unicamp, 2019) e "Imprensa Negra no Brasil do Século XIX" (Selo Negro, 2010). É ativista dos Movimentos Negros e de Mulheres Negras. Exerce a coordenação da regional Centro-Oeste do GT Emancipações e Pós-Abolição da Associação Nacional de História (Anpuh) e integra a Rede de Historiadoras Negras e Historiadores Negros.'
];