<?php

return [
    'title' => 'Producers',
    'ngongo' => "NGONGO Films was created by Mariana Luiza, with the goal of making literary,film and video projects related to ethnic, social, and gender issues. Throughout the years, the production company has provided services to Bananeira Filmes, Preta Portê Filmes, Conspiração Filmes and Coqueirão Pictures. In 2017, the production company finalized the short film “Casca de Baobá” (12 min). The film was awarded an Affirmative Short Film grant at the call for  grant proposals offered by the Ministry of Culture’s Film and Video Bureau (2014). Casca de Baobá was shown in several festivals in Brazil and around the world, receiving 6 awards. In 2010, the production company produced the medium-length film A B Ser (52 min).  The film was awarded  a grant at the call for  grant proposals offered by Filma Brasil public funding (Rouanet Law), and it was licensed to Futura channel.",
    'carapia' => "Carapiá Filmes was born from the desire to make cinema in a collaborative and human way. In our productions, we seek to  support emerging Latin American directors with the intention of producing films based on new ideas and perspectives. We are interested in projects  led by historically invisible people and with themes of strong artistic, political, and social appeal. To contribute to a new way of thinking and transforming our reality through cinema, we created our germinACTION center, a space for training and developing people in the film and video fields. We are currently developing and producing the projects: The Secret of Sikpan, with Everlane Moraes (Brlab, TorinoFilmLab, Brasil CineMundi, among others), Maestra with Bruna Piantino  benefited by the Municipal Law of Incentive to Culture of Belo Horizonte) and The Margin Color (BioBioLab, Brasil CineMundi, Miradas Doc, among others) with Mariana Luiza, a Brazil-France coproduction.",
    'vidigal' => "Fernanda is specialized in film production at EICTV/Cuba and graduated in Cinema and Audiovisual at UNA University Center/Brazil. Since 2013 she has been working in film production, she has worked on ten feature films. Fernanda is part of the Berlinale Talents Guadalajara (Mexico) and Talents Paradiso (Brazil) network. In 2020 she created her production company Carapiá Filmes, in Belo Horizonte. In 2021 she was invited by Project Paradiso to attend the Visitors Programme of the Berlinale Co-Production Market (Germany) and was part of the Foreign Project Selection Committee of BrLab Features (Brazil). Currently, Fernanda is developing three  films with three Brazilian directors,  one being a co-production with France, and winning  funding such as Hubert Bals Fund, BH nas Telas, and others.",
    'url_1' => "http://fernandavidigal.com.br/",
    'url_2' => "https://www.imdb.com/name/nm11710290/?ref_=nv_sr_srsg_0",
    'url_3' => "https://www.linkedin.com/in/fernanda-vidigal/",
    'parati' => "Parati Films, a French production company based in the Les Pays de la Loire region in France, has been working in the  film and video market since 2006. Recently, it opened a subsidiary in Rio de Janeiro, Brazil. In its mission to valorize authorial cinema and independent works in Latin America, with the support of its other departments, its work focuses mainly on the co-production of works between Latin America and Europe. For many years, the production company has chosen to absent itself from direct film production in order to concentrate especially on Brazil CineMundi and La Fabrique des cinemas du Monde. In 2022, the company returns to the market with all its energy and experience for production and co-production. ",
    'roinssart' => "Séverine started Parati Films in 2006, with the goal of creating a cinematic exchange program,  especially between France, Europe and Latin American countries  The dynamism of the 4 areas of Parati Films: - event organization and provision of services, subtitle & translation, production and management of educational content, has resulted in collaborations with countless professionals from the world of cinema and international festivals. One such example is the Cannes Film Festival, where since 2011 Parati has been the official partner of the Institut Francais in the selection of projects and the coordination of the La Fabrique des Cinémas du Monde program – and also participated in co-production projects. Parati is currently co-producing a Brazilian documentary film and a fiction  film from Paraguay. Finally, Séverine has just created the Crok Cine, programme for education - in and through images, in France and internationally, based on social mixing."
    ];


